In [2]:
!ls

sample_data

In [14]:
!ls drive/MyDrive/DataSet

16cbaf00248311ed.zip

In [13]:
!unzip gdrive/My\ Drive/data/train.zip > /dev/null

/bin/bash: drive/MyDrive/DataSet/: Is a directory

In [17]:
!ls dataset

sample_submission.csv  test  train

# Load the dataset into dataframe

In [18]:
import pandas as pd 
import numpy as np

In [33]:
d = {}
with open("dataset/train/1.txt") as f:
    for line in f:
      x = line.split()
      if (len(x) == 2):
        (key, val) = x
      else:
        if x[0] == "Weather":
          key = "Weather_conditions"
          val = x[2]
        elif x[0] == "Time_taken":
          key = "Time_taken_min"
          val = x[2]
        elif(len(x) == 4 and x[0] == "Name:"):
          # better error handling; ignore last name
          pass
        else:
          print(f'len > 2; {x}')
      d[key] = val

In [25]:
#print(d)

In [32]:
print(d)

{'ID': '0xb379', 'Delivery_person_ID': 'BANGRES18DEL02', 'Delivery_person_Age': '34.000000', 'Delivery_person_Ratings': '4.500000', 'Restaurant_latitude': '12.913041', 'Restaurant_longitude': '77.683237', 'Delivery_location_latitude': '13.043041', 'Delivery_location_longitude': '77.813237', 'Order_Date': '25-03-2022', 'Time_Orderd': '19:45', 'Time_Order_picked': '19:50', 'Weather_conditions': 'Stormy', 'Road_traffic_density': 'Jam', 'Vehicle_condition': '2', 'Type_of_order': 'Snack', 'Type_of_vehicle': 'scooter', 'multiple_deliveries': '1.000000', 'Festival': 'No', 'City': 'Metropolitian', 'Time_taken_min': '33.000000'}

In [45]:
import os
train_path='dataset/train/'
list_d = []
for filename in os.listdir(train_path):
   with open(os.path.join(train_path, filename), 'r') as f: # open in readonly mode
      # do your stuff
      # print(filename)
      d = {}
      for line in f:
        x = line.split()
        if (len(x) == 2):
          (key, val) = x
        else:
          if x[0] == "Weather":
            key = "Weather_conditions"
            val = x[2]
          elif x[0] == "Time_taken":
            key = "Time_taken_min"
            val = x[2]
          elif(len(x) == 4 and x[0] == "Name:"):
            # better error handling; ignore last name
            pass
          else:
            print(f'{filename}: len > 2; {x}')
        d[key] = val
      list_d.append(d)

In [46]:
print(len(list_d))

45593

In [47]:
train_df = pd.DataFrame(list_d)

In [49]:
train_df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken_min
0,0x43f7,COIMBRES20DEL02,24.000000,4.900000,10.994136,76.963303,11.124136,77.093303,29-03-2022,21:45,21:50,Windy,Jam,2,Snack,scooter,1.000000,No,Metropolitian,20.000000
1,0x5e38,HYDRES04DEL03,27.000000,4.900000,17.411028,78.329645,17.501028,78.419645,06-04-2022,21:35,21:40,Sandstorms,Jam,0,Meal,motorcycle,1.000000,No,Urban,38.000000
2,0x9039,JAPRES18DEL01,37.000000,4.300000,26.913987,75.752891,26.953987,75.792891,26-03-2022,15:10,15:15,Stormy,Medium,0,Meal,motorcycle,1.000000,No,Urban,33.000000
3,0xd3cb,KOLRES19DEL02,27.000000,4.900000,22.549100,88.400467,22.569100,88.420467,13-02-2022,11:50,11:60,Fog,High,1,Snack,motorcycle,1.000000,No,Metropolitian,21.000000
4,0x9117,HYDRES12DEL03,29.000000,4.500000,17.429585,78.392621,17.489585,78.452621,17-03-2022,18:25,18:40,Sunny,Medium,1,Snack,motorcycle,0.000000,No,Metropolitian,12.000000

In [54]:
train_df.to_csv(r'drive/MyDrive/DataSet/dataset/train_ds.csv', index=False)

In [55]:
!ls drive/MyDrive/DataSet/dataset/

sample_submission.csv  test  train  train_ds.csv

In [56]:
import os
train_path='dataset/test/'
list_d = []
for filename in os.listdir(train_path):
   with open(os.path.join(train_path, filename), 'r') as f: # open in readonly mode
      # do your stuff
      # print(filename)
      d = {}
      for line in f:
        x = line.split()
        if (len(x) == 2):
          (key, val) = x
        else:
          if x[0] == "Weather":
            key = "Weather_conditions"
            val = x[2]
          elif x[0] == "Time_taken":
            key = "Time_taken_min"
            val = x[2]
          elif(len(x) == 4 and x[0] == "Name:"):
            # better error handling; ignore last name
            pass
          else:
            print(f'{filename}: len > 2; {x}')
        d[key] = val
      list_d.append(d)

In [57]:
print(len(list_d))

11399

In [58]:
test_df = pd.DataFrame(list_d)

In [59]:
test_df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
0,0x1227,COIMBRES06DEL02,37.000000,4.500000,11.021278,76.995017,11.151278,77.125017,18-03-2022,22:10,22:20,Sandstorms,Low,2,Buffet,scooter,1.000000,No,Metropolitian
1,0x8089,MUMRES08DEL01,25.000000,4.700000,19.065838,72.832658,19.075838,72.842658,03-03-2022,11:15,11:20,Windy,High,0,Snack,motorcycle,NaN,Yes,Metropolitian
2,0x8980,MUMRES06DEL01,20.000000,4.800000,19.055831,72.833984,19.125831,72.903984,31-03-2022,22:30,22:35,Fog,Low,0,Drinks,motorcycle,1.000000,No,NaN
3,0x4930,COIMBRES20DEL02,35.000000,4.600000,10.994136,76.963303,11.074136,77.043303,27-03-2022,22:55,23:10,Stormy,Low,1,Buffet,scooter,0.000000,No,Metropolitian
4,0x2f25,INDORES12DEL03,38.00000,4.90000,22.74806,75.89340,22.77806,75.92340,03-03-2022,22:60,23:10,Cloudy,Low,1,Meal,scooter,0.00000,No,Metropolitian

In [60]:
test_df.to_csv(r'drive/MyDrive/DataSet/dataset/test_ds.csv', index=False)